name: "💡 Solicitação de Funcionalidade"
description: Crie um novo ticket para uma nova solicitação de funcionalidade
title: "💡 [SOLICITAÇÃO] - <título>"
labels: [
  "pergunta"
]
body:
  - type: textarea
    id: summary
    attributes:
      label: "Resumo"
      description: Forneça uma breve explicação da funcionalidade
      placeholder: Descreva em algumas linhas sua solicitação de funcionalidade
    validations:
      required: false
