# Generated by Django 5.1.7 on 2025-03-25 23:13

import django.db.models.deletion
import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('idade', models.IntegerField()),
                ('curso', models.CharField(max_length=255)),
                ('ira', models.DecimalField(decimal_places=2, max_digits=4)),
                ('email', models.EmailField(max_length=254)),
                ('lattes', models.URLField()),
                ('github', models.URLField()),
                ('interesse', models.CharField(max_length=255)),
                ('genero', models.CharField(max_length=50)),
                ('ppi', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=11)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'alunos',
            },
        ),
        migrations.CreateModel(
            name='Edital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('arquivo', models.FileField(upload_to='editais/')),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
                ('autor', models.CharField(max_length=100)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Arquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=255)),
                ('arquivo', models.FileField(upload_to=home.models.arquivo_upload_path)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='home.aluno')),
            ],
        ),
    ]
