# Generated by Django 5.0.6 on 2024-12-07 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('idade', models.IntegerField()),
                ('curso', models.CharField(max_length=255)),
                ('ira', models.DecimalField(decimal_places=2, max_digits=4)),
                ('email', models.EmailField(max_length=254)),
                ('lattes', models.URLField()),
                ('github', models.URLField()),
                ('interesse', models.CharField(max_length=255)),
                ('genero', models.CharField(max_length=50)),
                ('ppi', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=11)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'meu_nome_personalizado_da_tabela',
            },
        ),
        migrations.CreateModel(
            name='Arquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=255)),
                ('arquivo', models.FileField(upload_to='')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='home.aluno')),
            ],
        ),
    ]
