# Generated by Django 5.1.7 on 2025-03-21 21:00

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivo',
            name='arquivo',
            field=models.FileField(upload_to=home.models.arquivo_upload_path),
        ),
    ]
