# Generated by Django 5.1.7 on 2025-05-15 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('ordem', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='selecao',
            name='quantidade_de_fases',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='CampoFase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('texto', 'Texto'), ('numero', 'Número'), ('data', 'Data'), ('arquivo', 'Arquivo')], max_length=20)),
                ('obrigatorio', models.BooleanField(default=False)),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campos', to='home.fase')),
            ],
        ),
        migrations.AddField(
            model_name='selecao',
            name='fases',
            field=models.ManyToManyField(related_name='selecoes', to='home.fase'),
        ),
        migrations.CreateModel(
            name='ValorCampoFase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_texto', models.TextField(blank=True, null=True)),
                ('valor_numero', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_data', models.DateField(blank=True, null=True)),
                ('valor_arquivo', models.FileField(blank=True, null=True, upload_to='fases/campos/')),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='home.campofase')),
                ('inscricao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores_campos', to='home.inscricao')),
            ],
        ),
    ]
