# Generated by Django 5.1.7 on 2025-05-28 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_fase_selecao_quantidade_de_fases_campofase_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCampo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('tipo_dado', models.CharField(choices=[('texto', 'Texto'), ('numero', 'Número'), ('data', 'Data'), ('arquivo', 'Arquivo'), ('escolha', 'Escolha Única'), ('multipla', 'Escolha Múltipla'), ('booleano', 'Verdadeiro/Falso')], max_length=20)),
                ('opcoes', models.TextField(blank=True, help_text='Para campos de escolha, informe uma opção por linha')),
            ],
            options={
                'verbose_name': 'Tipo de Campo',
                'verbose_name_plural': 'Tipos de Campo',
            },
        ),
        migrations.AlterModelOptions(
            name='aluno',
            options={'verbose_name': 'Aluno', 'verbose_name_plural': 'Alunos'},
        ),
        migrations.AlterModelOptions(
            name='campofase',
            options={'ordering': ['ordem'], 'verbose_name': 'Campo da Fase', 'verbose_name_plural': 'Campos da Fase'},
        ),
        migrations.AlterModelOptions(
            name='edital',
            options={'ordering': ['-data_publicacao'], 'verbose_name': 'Edital', 'verbose_name_plural': 'Editais'},
        ),
        migrations.AlterModelOptions(
            name='fase',
            options={'ordering': ['ordem'], 'verbose_name': 'Fase', 'verbose_name_plural': 'Fases'},
        ),
        migrations.AlterModelOptions(
            name='inscricao',
            options={'ordering': ['-data_inscricao'], 'verbose_name': 'Inscrição', 'verbose_name_plural': 'Inscrições'},
        ),
        migrations.AlterModelOptions(
            name='professor',
            options={'verbose_name': 'Professor', 'verbose_name_plural': 'Professores'},
        ),
        migrations.AlterModelOptions(
            name='selecao',
            options={'ordering': ['-data_inicio'], 'verbose_name': 'Seleção', 'verbose_name_plural': 'Seleções'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.AlterModelOptions(
            name='valorcampofase',
            options={'verbose_name': 'Valor de Campo', 'verbose_name_plural': 'Valores de Campos'},
        ),
        migrations.RemoveField(
            model_name='selecao',
            name='fases',
        ),
        migrations.RemoveField(
            model_name='selecao',
            name='quantidade_de_fases',
        ),
        migrations.AddField(
            model_name='campofase',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='campofase',
            name='peso',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Peso deste campo na avaliação da fase', max_digits=5),
        ),
        migrations.AddField(
            model_name='edital',
            name='nota_minima_aprovacao',
            field=models.DecimalField(decimal_places=2, default=7.0, help_text='Nota mínima para aprovação nas fases (0-10)', max_digits=4),
        ),
        migrations.AddField(
            model_name='fase',
            name='data_fim',
            field=models.DateTimeField(default='2001-09-11 00:00:00', help_text='Use o formato YYYY-MM-DD HH:MM[:ss[.uuuuuu]][TZ]'),
        ),
        migrations.AddField(
            model_name='fase',
            name='data_inicio',
            field=models.DateTimeField(default='2001-09-10 00:00:00', help_text='Use o formato YYYY-MM-DD HH:MM[:ss[.uuuuuu]][TZ]'),
        ),
        migrations.AddField(
            model_name='fase',
            name='obrigatoria',
            field=models.BooleanField(default=True, help_text='Se a fase é obrigatória para aprovação'),
        ),
        migrations.AddField(
            model_name='fase',
            name='peso',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Peso desta fase na avaliação final (0-1)', max_digits=5),
        ),
        migrations.AddField(
            model_name='fase',
            name='selecao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fases_selecao', to='home.selecao'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='nota_final',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='selecao',
            name='quantidade_fases',
            field=models.PositiveIntegerField(default=1, help_text='Número total de fases do processo seletivo'),
        ),
        migrations.AddField(
            model_name='valorcampofase',
            name='avaliacao',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Nota atribuída pelo avaliador (0-10)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='valorcampofase',
            name='observacao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='valorcampofase',
            name='valor_booleano',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='selecao',
            name='data_fim',
            field=models.DateTimeField(default='2001-09-11 00:00:00', help_text='Use o formato YYYY-MM-DD HH:MM[:ss[.uuuuuu]][TZ]'),
        ),
        migrations.AlterField(
            model_name='selecao',
            name='data_inicio',
            field=models.DateTimeField(default='2001-09-10 00:00:00', help_text='Use o formato YYYY-MM-DD HH:MM[:ss[.uuuuuu]][TZ]'),
        ),
        migrations.AlterUniqueTogether(
            name='campofase',
            unique_together={('fase', 'ordem')},
        ),
        migrations.AlterUniqueTogether(
            name='fase',
            unique_together={('selecao', 'ordem')},
        ),
        migrations.AlterUniqueTogether(
            name='valorcampofase',
            unique_together={('campo', 'inscricao')},
        ),
        migrations.AlterField(
            model_name='campofase',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campos_fase', to='home.tipocampo'),
        ),
        migrations.CreateModel(
            name='AvaliacaoFase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(decimal_places=2, max_digits=5)),
                ('aprovado', models.BooleanField(default=False)),
                ('observacoes', models.TextField(blank=True)),
                ('data_avaliacao', models.DateTimeField(auto_now_add=True)),
                ('avaliador', models.ForeignKey(limit_choices_to={'tipo_usuario': 'professor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avaliacoes_realizadas', to=settings.AUTH_USER_MODEL)),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='home.fase')),
                ('inscricao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_fases', to='home.inscricao')),
            ],
            options={
                'verbose_name': 'Avaliação de Fase',
                'verbose_name_plural': 'Avaliações de Fases',
                'ordering': ['-data_avaliacao'],
                'unique_together': {('fase', 'inscricao', 'avaliador')},
            },
        ),
    ]
