# Generated by Django 5.1.7 on 2025-05-28 14:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_tipocampo_alter_aluno_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fase',
            name='obrigatoria',
        ),
        migrations.AddField(
            model_name='fase',
            name='tipo_fase',
            field=models.CharField(choices=[('classificatoria', 'Classificatória'), ('eliminatoria', 'Eliminatória')], default='classificatoria', max_length=15),
        ),
        migrations.AlterField(
            model_name='fase',
            name='data_fim',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Use o formato YYYY-MM-DD HH:MM[:ss[.uuuuuu]][TZ]'),
        ),
        migrations.AlterField(
            model_name='fase',
            name='data_inicio',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Use o formato YYYY-MM-DD HH:MM[:ss[.uuuuuu]][TZ]'),
        ),
        migrations.AlterField(
            model_name='selecao',
            name='data_fim',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Use o formato YYYY-MM-DD HH:MM[:ss[.uuuuuu]][TZ]'),
        ),
        migrations.AlterField(
            model_name='selecao',
            name='data_inicio',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Use o formato YYYY-MM-DD HH:MM[:ss[.uuuuuu]][TZ]'),
        ),
    ]
