# Generated by Django 5.1.7 on 2025-05-30 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_fase_obrigatoria_fase_tipo_fase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='fase_atual',
            field=models.PositiveIntegerField(default=1, help_text='Fase atual do processo seletivo'),
        ),
    ]
