# Generated by Django 5.1.7 on 2025-05-30 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_inscricao_fase_atual'),
    ]

    operations = [
        migrations.AddField(
            model_name='fase',
            name='nota_corte',
            field=models.DecimalField(blank=True, decimal_places=2, default=7.0, help_text='Nota mínima para aprovação nesta fase (0-10)', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='fase',
            name='numero_vagas',
            field=models.PositiveIntegerField(blank=True, default=1, help_text='Número de inscrições que avançam para a próxima fase', null=True),
        ),
    ]
