# Generated by Django 5.1.7 on 2025-05-30 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_fase_nota_corte_fase_numero_vagas'),
    ]

    operations = [
        migrations.AddField(
            model_name='fase',
            name='status',
            field=models.CharField(choices=[('não iniciada', 'Não iniciada'), ('atual', 'Atual'), ('finalizada', 'Finalizada')], default='ativa', help_text='Status atual da fase', max_length=20),
        ),
        migrations.AddField(
            model_name='selecao',
            name='fase_atual',
            field=models.PositiveIntegerField(default=1, help_text='Fase atual do processo seletivo'),
        ),
    ]
