# Generated by Django 5.1.7 on 2025-06-02 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_fase_status_selecao_fase_atual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fase',
            name='status',
            field=models.CharField(choices=[('não iniciada', 'Não iniciada'), ('atual', 'Atual'), ('finalizada', 'Finalizada')], default='não iniciada', help_text='Status atual da fase', max_length=20),
        ),
    ]
